
package com.huawei.bme.cbsinterface.querymgr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QueryMgr", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.huawei.bme.cbsinterface.common.ObjectFactory.class,
    com.huawei.bme.cbsinterface.subscribe.ObjectFactory.class,
    com.huawei.bme.cbsinterface.newsubscriber.ObjectFactory.class,
    com.huawei.bme.cbsinterface.query.ObjectFactory.class,
    com.huawei.bme.cbsinterface.acctcredit.ObjectFactory.class,
    com.huawei.bme.cbsinterface.querymgr.ObjectFactory.class
})
public interface QueryMgr {


    /**
     * 
     * @param queryCustomerRequestMsg
     * @return
     *     returns com.huawei.bme.cbsinterface.querymgr.QueryCustomerResultMsg
     */
    @WebMethod(action = "queryCustomer")
    @WebResult(name = "QueryCustomerResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryCustomerResultMsg")
    public QueryCustomerResultMsg queryCustomer(
        @WebParam(name = "QueryCustomerRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryCustomerRequestMsg")
        QueryCustomerRequestMsg queryCustomerRequestMsg);

    /**
     * 
     * @param queryBalanceRequestMsg
     * @return
     *     returns com.huawei.bme.cbsinterface.querymgr.QueryBalanceResultMsg
     */
    @WebMethod(action = "queryBalance")
    @WebResult(name = "QueryBalanceResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryBalanceResultMsg")
    public QueryBalanceResultMsg queryBalance(
        @WebParam(name = "QueryBalanceRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryBalanceRequestMsg")
        QueryBalanceRequestMsg queryBalanceRequestMsg);

    /**
     * 
     * @param queryProductOrderRequestMsg
     * @return
     *     returns com.huawei.bme.cbsinterface.querymgr.QueryProductOrderResultMsg
     */
    @WebMethod(action = "queryProductOrder")
    @WebResult(name = "QueryProductOrderResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryProductOrderResultMsg")
    public QueryProductOrderResultMsg queryProductOrder(
        @WebParam(name = "QueryProductOrderRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryProductOrderRequestMsg")
        QueryProductOrderRequestMsg queryProductOrderRequestMsg);

    /**
     * 
     * @param queryLastTranInfoRequestMsg
     * @return
     *     returns com.huawei.bme.cbsinterface.querymgr.QueryLastTranInfoResultMsg
     */
    @WebMethod(action = "queryLastTranInfo")
    @WebResult(name = "QueryLastTranInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryLastTranInfoResultMsg")
    public QueryLastTranInfoResultMsg queryLastTranInfo(
        @WebParam(name = "QueryLastTranInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryLastTranInfoRequestMsg")
        QueryLastTranInfoRequestMsg queryLastTranInfoRequestMsg);

    /**
     * 
     * @param queryBalanceTransferInfoRequestMsg
     * @return
     *     returns com.huawei.bme.cbsinterface.querymgr.QueryBalanceTransferInfoResultMsg
     */
    @WebMethod(action = "queryBalanceTransferInfo")
    @WebResult(name = "QueryBalanceTransferInfoResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryBalanceTransferInfoResultMsg")
    public QueryBalanceTransferInfoResultMsg queryBalanceTransferInfo(
        @WebParam(name = "QueryBalanceTransferInfoRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QueryBalanceTransferInfoRequestMsg")
        QueryBalanceTransferInfoRequestMsg queryBalanceTransferInfoRequestMsg);

    /**
     * 
     * @param querySubCosIDRequestMsg
     * @return
     *     returns com.huawei.bme.cbsinterface.querymgr.QuerySubCosIDResultMsg
     */
    @WebMethod(action = "querySubCosID")
    @WebResult(name = "QuerySubCosIDResultMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QuerySubCosIDResultMsg")
    public QuerySubCosIDResultMsg querySubCosID(
        @WebParam(name = "QuerySubCosIDRequestMsg", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr", partName = "QuerySubCosIDRequestMsg")
        QuerySubCosIDRequestMsg querySubCosIDRequestMsg);

}
