
package com.huawei.bme.cbsinterface.querymgr;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.apache.log4j.Logger;

import com.emagine.querybal.config.PropertiesLoader;
import com.emagine.querybal.utils.QueryBalanceConstant;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QueryMgrService", targetNamespace = "http://www.huawei.com/bme/cbsinterface/querymgr")
public class QueryMgrService extends Service {
    private static final Logger LOGGER = Logger.getLogger(QueryMgrService.class);
    private final static URL QUERYMGRSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYMGRSERVICE_EXCEPTION;
    private final static QName QUERYMGRSERVICE_QNAME = new QName("http://www.huawei.com/bme/cbsinterface/querymgr", "QueryMgrService");

    static {
        LOGGER.debug("QueryMgrService static block");
        URL url = null;
        WebServiceException e = null;
        try {
            String wsdlLoc = PropertiesLoader.getValue(QueryBalanceConstant.OCS_QRY_MGR_WSDL_LOC);
            url = new URL(wsdlLoc);
            // url = new
            // URL("http://10.10.20.40:7782/services/QueryMgrService?wsdl");
        } catch (MalformedURLException ex) {

            e = new WebServiceException(ex);
            LOGGER.error("QueryMgrService static block error ", e);
        } catch (Exception e1) {
            e = new WebServiceException(e1);
            LOGGER.error("QueryMgrService static block error ", e);
            e1.printStackTrace();
        }
        QUERYMGRSERVICE_WSDL_LOCATION = url;
        QUERYMGRSERVICE_EXCEPTION = e;
        LOGGER.debug("QueryMgrService static block end");
    }

    public QueryMgrService() {
        super(__getWsdlLocation(), QUERYMGRSERVICE_QNAME);
    }

    public QueryMgrService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYMGRSERVICE_QNAME, features);
    }

    public QueryMgrService(URL wsdlLocation) {
        super(wsdlLocation, QUERYMGRSERVICE_QNAME);
    }

    public QueryMgrService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYMGRSERVICE_QNAME, features);
    }

    public QueryMgrService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryMgrService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns QueryMgr
     */
    @WebEndpoint(name = "QueryMgrServicePort")
    public QueryMgr getQueryMgrServicePort() {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/querymgr", "QueryMgrServicePort"), QueryMgr.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns QueryMgr
     */
    @WebEndpoint(name = "QueryMgrServicePort")
    public QueryMgr getQueryMgrServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.huawei.com/bme/cbsinterface/querymgr", "QueryMgrServicePort"), QueryMgr.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYMGRSERVICE_EXCEPTION != null) {
            throw QUERYMGRSERVICE_EXCEPTION;
        }
        return QUERYMGRSERVICE_WSDL_LOCATION;
    }

}
